version: '3.3'

services:
  postgresdb:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=jeffer
      - POSTGRES_PASSWORD=jay123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jortizr@ut.edu.co
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=jay123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
    - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=jay123
      - PMA_HOST=mysql
    ports:
      - 8080:80
