version: '3.3'

services:
  postgresdb:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=jeffer
      - POSTGRES_PASSWORD=jay123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jortizr@ut.edu.co
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
